name: pull and bear

on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 */8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4
          pip install email
      - name: run pull
        run: |
          python -m pull

  
